### ISSUE TITLE
Difference between hipster_empath and c_hipster_empath?

### ISSUE THREAD

**Issue by frastlin** [manoelhortaribeiro/AbusiveUsersOSNs#1]
Hello,
I am trying to understand this data set to build a representation. I'm a little confused at the difference between hipster_empath and c_hipster_empath.
The documentation says:

  [c_] *_empath :float
  occurrences of empath categories in the users latest 200 tweets.

This is only the c_hipster_empath. There is no documentation I see for just hipster_empath.
For now I'll just use c_hipster_empath, but I would like to know the difference between the two.
Thanks,

**Comment by manoelhortaribeiro** [comment]
Hey frastling, the idea is that hipster_empath is the empath category for a given user, whereas hipster_empath_c is the average of the value of hispter_empath  for all users connected to that user!

Makes sense?

**Comment by frastlin** [comment]
yes thank you! so it is the community score for that person.
