### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by Michael-OMahony** [manoelhortaribeiro/AbusiveUsersOSNs#4]
Hello, could you send me the dataset, please?

**Comment by Sopamo** [comment]
The dataset is available here: https://www.kaggle.com/manoelribeiro/hateful-users-on-twitter

**Comment by abrahami** [comment]
hi, is the process of running the DeGroot’s model included in the code? I have not seen it. If not - how exactly did you run it?

thank you!

**Comment by manoelhortaribeiro** [comment]
See here: 

https://github.com/manoelhortaribeiro/HatefulUsersTwitter/blob/master/preprocessing/5_get_diffusion_graph.py

Data for reproducing this is not available, however.

**Comment by abrahami** [comment]
Awesome - thank you!
